### ISSUE TITLE
unit test order creation

### ISSUE THREAD

**Issue by moodysalem** [EkuboProtocol/limit-orders-extension#1]
- it initializes pool on correct side of order (depending on tick, the order is either for token1 or token0)
- creates the core position with the correct parameters
- order info can be queried afterwards via view method and returns correct result

will need to create a contract for placing the limit order via the `core#forward` functionality just for testing. this functionality will be integrated into the positions contract later, so no need to make this contract production ready.

**Comment by oxlime** [comment]
would like to work on this issue.

**Comment by moodysalem** [comment]
> would like to work on this issue.

Great! Let me know if you have any questions

**Comment by moodysalem** [comment]
@oxlime have you started on this? If not, I will start on it
